#localhost:3306-root-testedb-root
version: '3'

services:
  mysqlsrv:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    #    volumes:
    #      - ../../data/mysql:/var/lib/postgresql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testedb
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network


networks:
  mysql-compose-network:
    driver: bridge

#docker-compose -f mysql.yml up