# https://hub.docker.com/u/edsonxp/content/sub-575458e8-4170-4997-b1f1-f11bd9bce629
#localhost:/ORCLCDB.localdomain-sys as sysdba-Oradoc_db1
#to add new users
#docker exec -it oracle bash -c "source /home/oracle/.bashrc; sqlplus /nolog"
version: '3.1'

services:

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1 #container-registry.oracle.com/database/enterprise:12.2.0.1
    container_name: "oracle"
    restart: always
    #    volumes:
    #      - ../../data/oracle:/ORCL
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 1521:1521


#docker-compose -f oracle-12.2.0.1.yml up
